# Send Governance Alert - Telegram Delivery
# Sends governance alerts via Telegram when drift or compliance issues detected

param(
    [Parameter(Mandatory=$true)]
    [string[]]$AlertReasons,
    
    [Parameter(Mandatory=$true)]
    [double]$ComplianceRate,
    
    [bool]$DriftDetected = $false,
    [double]$DriftPercentage = 0,
    [int]$TotalViolations = 0,
    [string]$ConfigPath = "$env:USERPROFILE\.openclaw\governance\config.json"
)

# Log alert to file for audit trail (DEFINED FIRST)
function Log-AlertToFile {
    param(
        [string[]]$AlertReasons,
        [double]$ComplianceRate,
        [bool]$Sent = $false
    )
    
    $AlertLogPath = "$env:USERPROFILE\.openclaw\governance\alerts.log"
    $LogEntry = @{
        timestamp = (Get-Date -Format "o")
        reasons = $AlertReasons
        complianceRate = $ComplianceRate
        alertSent = $Sent
    } | ConvertTo-Json -Compress
    
    try {
        # Ensure directory exists
        $Dir = Split-Path $AlertLogPath -Parent
        if (-not (Test-Path $Dir)) {
            New-Item -ItemType Directory -Path $Dir -Force | Out-Null
        }
        
        Add-Content -Path $AlertLogPath -Value $LogEntry
        Write-Host "  ✓ Alert logged to: $AlertLogPath" -ForegroundColor Gray
    } catch {
        Write-Host "  ⚠️  Failed to log alert: $_" -ForegroundColor Yellow
    }
}

Write-Host "=== Send Governance Alert ===" -ForegroundColor Cyan

# Load Telegram config from openclaw.json
$OpenClawConfigPath = "$env:USERPROFILE\.openclaw\openclaw.json"
if (-not (Test-Path $OpenClawConfigPath)) {
    Write-Host "  ⚠️  openclaw.json not found at: $OpenClawConfigPath" -ForegroundColor Yellow
    Write-Host "  Cannot send Telegram alert - logging to file instead" -ForegroundColor Gray
    Log-AlertToFile -AlertReasons $AlertReasons -ComplianceRate $ComplianceRate
    exit 0  # Graceful degradation - logging is acceptable fallback
}

try {
    $OpenClawConfig = Get-Content $OpenClawConfigPath -Raw | ConvertFrom-Json
    $BotToken = $OpenClawConfig.channels.telegram.botToken
    $ChatId = $OpenClawConfig.channels.telegram.chatId
    
    if (-not $BotToken -or -not $ChatId) {
        Write-Host "  ⚠️  Telegram bot token or chat ID not configured in openclaw.json" -ForegroundColor Yellow
        Write-Host "  Alert logged but not sent." -ForegroundColor Gray
        Log-AlertToFile -AlertReasons $AlertReasons -ComplianceRate $ComplianceRate
        exit 0  # Graceful degradation
    }
} catch {
    Write-Host "  ⚠️  Failed to load Telegram config: $_" -ForegroundColor Yellow
    Log-AlertToFile -AlertReasons $AlertReasons -ComplianceRate $ComplianceRate
    exit 0  # Graceful degradation
}

# Build alert message
$Message = "⚠️ *Governance Alert*`n`n"

foreach ($Reason in $AlertReasons) {
    $Message += "• $Reason`n"
}

$Message += "`n*Current Metrics:*`n"
$Message += "• Compliance Rate: $([Math]::Round($ComplianceRate * 100, 1))%`n"
$Message += "• Total Violations (7d): $TotalViolations`n"

if ($DriftDetected) {
    $Message += "• Drift: +$([Math]::Round($DriftPercentage * 100, 1))%`n"
}

$Message += "`n*Action Required:* Review governance dashboard and address root causes.`n"
$Message += "_Auto-generated by governance-analyzer.ps1 (Phase 1B)_"

Write-Host "`nSending Telegram alert..." -ForegroundColor Cyan
Write-Host "Bot Token: $($BotToken.Substring(0, 10))..." -ForegroundColor Gray
Write-Host "Chat ID: $ChatId" -ForegroundColor Gray

# Send to Telegram
$Url = "https://api.telegram.org/bot$BotToken/sendMessage"
$Body = @{
    chat_id = $ChatId
    text = $Message
    parse_mode = "Markdown"
} | ConvertTo-Json

try {
    $Response = Invoke-RestMethod -Uri $Url -Method Post -Body $Body -ContentType "application/json; charset=utf-8"
    if ($Response.ok) {
        Write-Host "  ✓ Telegram alert sent successfully" -ForegroundColor Green
        Log-AlertToFile -AlertReasons $AlertReasons -ComplianceRate $ComplianceRate -Sent:$true
        exit 0
    } else {
        Write-Host "  ✗ Telegram API error: $($Response.description)" -ForegroundColor Red
        Log-AlertToFile -AlertReasons $AlertReasons -ComplianceRate $ComplianceRate
        exit 0  # Alert logged, so not a total failure
    }
} catch {
    Write-Host "  ✗ Failed to send Telegram alert: $_" -ForegroundColor Red
    Write-Host "  Error Details: $($_.Exception.Message)" -ForegroundColor Gray
    Log-AlertToFile -AlertReasons $AlertReasons -ComplianceRate $ComplianceRate
    exit 0  # Alert logged, so not a total failure
}
