/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  DS_HearthGovernor,
  DS_HearthGovernorInterface,
} from "../../contracts/DS_HearthGovernor";

const _abi = [
  {
    inputs: [],
    name: "getQuorum",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f80fd5b50607480601a5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c8063c26c12eb14602a575b5f80fd5b600460405190815260200160405180910390f3fea2646970667358221220409eacbb63b845727fcfab0958af7d8b46c7d3c3fa9f533da388124904a3685264736f6c63430008180033";

type DS_HearthGovernorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DS_HearthGovernorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DS_HearthGovernor__factory extends ContractFactory {
  constructor(...args: DS_HearthGovernorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      DS_HearthGovernor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DS_HearthGovernor__factory {
    return super.connect(runner) as DS_HearthGovernor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DS_HearthGovernorInterface {
    return new Interface(_abi) as DS_HearthGovernorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): DS_HearthGovernor {
    return new Contract(address, _abi, runner) as unknown as DS_HearthGovernor;
  }
}
